import "./globals.css";
// import { Karla } from "next/font/google";
import Providers from "./providers";

// const font = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "AI avatar project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
