import { Karla, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const font = Karla({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI avatar project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
